name: CI

# run on all branches for PRs opened
on:
  pull_request:
    branches:
      - '**'

jobs:
  run-all-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          # java 11 does not support expected jvm arguments
          java-version: 8

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Full Tests
        run: |
          ./gradlew clean check -i